export const words = [
    "amigo", "amora", "amplo", "andar", "anexo", "animo", "antes", "apego", "arena", "armao",
    "asilo", "astro", "ativo", "atlas", "atrio", "aviao", "bambu", "banco", "barra", "beijo",
    "besta", "blefa", "bomba", "borda", "bravo", "brejo", "breve", "brisa", "broto", "bruxa",
    "burro", "busca", "busto", "caixa", "caldo", "campo", "canal", "canto", "carbon", "cargo",
    "carne", "carro", "casal", "casca", "causa", "ceder", "cegar", "cerco", "cerne", "chave",
    "cheio", "chefe", "choro", "ciclo", "cinto", "circo", "citar", "civil", "clima", "clube",
    "cobre", "cocar", "cocar", "cogum", "coisa", "colar", "comer", "comum", "conde", "coral",
    "corpo", "corso", "corte", "couro", "cravo", "creme", "criar", "crime", "crise", "cruel",
    "dados", "danar", "dança", "deixa", "dente", "denso", "depor", "desce", "digna", "digno",
    "dique", "disco", "ditar", "doado", "doada", "dogma", "dolar", "domar", "dorme", "drama",
    "droga", "ducha", "dunas", "ecoar", "elite", "elogio", "energia", "enfim", "enxoo",
    "ereto", "errar", "escor", "esmal", "espia", "estar", "etapa", "exame", "extra", "falar",
    "fardo", "farto", "fatal", "favor", "fazer", "feria", "feroz", "festa", "ficar", "ficha",
    "firme", "folha", "forma", "forte", "fosco", "fraco", "freio", "friso", "fruto", "fugiu",
    "fundo", "fusao", "gaita", "galho", "ganso", "garra", "garfo", "gente", "geral", "gerir",
    "gesso", "gigio", "girar", "gosto", "grato", "greve", "grade", "grupo", "gueto", "harpa",
    "haste", "heroi", "hiena", "horda", "humor", "ideal", "idoso", "impar", "impio", "indio",
    "infla", "inves", "irado", "isca", "janta", "jeito", "jogar", "jovem", "juizo", "julho",
    "junho", "justo", "labia", "lacre", "lagoa", "lance", "lapis", "larga", "largo", "latir",
    "leito", "leite", "lento", "leste", "levar", "lider", "lindo", "linha", "livre", "lixar",
    "louco", "louro", "lutar", "luzir", "macho", "magra", "magro", "malao", "malha", "manga",
    "manha", "manso", "matar", "meigo", "meios", "melar", "melho", "menos", "mente", "merda",
    "mesmo", "metal", "metro", "misto", "mitos", "moeda", "moita", "molar", "morno", "morto",
    "mudar", "muito", "mural", "musgo", "natal", "navio", "negar", "nervo", "nivel", "nobre",
    "nocao", "noite", "norte", "nuvem", "obeso", "obrar", "ocaso", "odiar", "olhar", "ombro",
    "opcao", "ordem", "orgao", "orixa", "ossos", "otimo", "ouvir", "ousar", "pacto", "padre",
    "pagar", "palco", "pardo", "parir", "parte", "pasmo", "patos", "pedra", "penso", "perda",
    "perna", "perto", "pesar", "peito", "piano", "pilar", "pinta", "pista", "plano", "pobre",
    "poder", "poema", "ponto", "porco", "porte", "posse", "prado", "presa", "preto", "prima",
    "primo", "prosa", "prova", "pular", "quero", "quire", "rabos", "raios", "raiva", "ranho",
    "rapaz", "raras", "rasgo", "ratos", "razao", "rever", "rezar", "ricas", "ricos", "rifle",
    "risco", "ritmo", "roubo", "ruido", "rumor", "saber", "sabor", "sadio", "saldo", "salto",
    "santo", "sapos", "seara", "seita", "selar", "selva", "setor", "sexta", "sinal", "sitio",
    "sobre", "solda", "somar", "sonho", "sopro", "sorte", "sutil", "tabua", "tacho", "talho",
    "tanto", "tarde", "telao", "temer", "tenue", "tesao", "texto", "tigre", "tinta", "tocar",
    "torre", "tosco", "trama", "trapo", "treta", "tribo", "trigo", "troca", "turbo", "turma",
    "ufano", "ultra", "umbro", "uniao", "urubu", "vagar", "vazio", "velho", "venda", "verao",
    "verba", "verde", "verme", "verso", "vetar", "vibra", "vicio", "video", "vinho", "vital",
    "viver", "voado", "vocal", "vodka", "volta", "vulgo", "xampu", "xingo", "zebra", "zumbi"
];

export const getRandomWord = (): string => {
    return words[Math.floor(Math.random() * words.length)].toUpperCase();
}
